- name: Checking for prior rust packages
  ansible.builtin.stat:
    path: ~/.cargo/bin/rustup
  register: rustup

- name: Installing rustup
  ansible.builtin.shell: sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs) -y"
  when: not rustup.stat.exists

- name: Updating rust toolchain
  ansible.builtin.shell: rustup update
  when: rustup.stat.exists

