- hosts: localhost
  vars:
    current_user: "{{ ansible_user_id }}"
  roles:
    - git

    # Programming Languages
    - rust
    - nodejs

    # Desktop Applications
    - firefox
    - terminal
    - vscode
    - virtualbox
    - joplin

    # Local System Conf
    - systemconf
