- name: Checking for homebrew
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew

- name: Installing homebrew
  ansible.builtin.shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew.stat.exists

- name: Install rlwrap
  community.general.homebrew:
    name: rlwrap
    state: latest
    update_homebrew: true

- name: Checking for clojure
  ansible.builin.stat:
    path: /usr/local/bin/clj
  register: clj

- name: Install clojure
  ansible.builtin.shell: bash -c "$(curl -O https://download.clojure.org/install/linux-install-1.10.3.943.sh)"
  when: not clj.stat.exists

