- name: Checking for homebrew
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew

- name: Installing homebrew
  ansible.builtin.shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew.stat.exists

- name: Install clojure package
  community.general.homebrew:
    name: clojure/tools/clojure
    state: latest
    update_homebrew: true
