- name: Checking for prior nvm package
  ansible.builtin.stat:
    path: ~/.nvm
  register: nvm

- name: Install nvm
  ansible.builtin.shell: bash -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh)"
  when: not nvm.stat.exists

- name: Configure nvm with zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: "{{ item.regexp }} "
    line: "{{ item.line }} "
  loop:
    - { regexp: '^export NVM_HOME=', line: 'export NVM_DIR="$HOME/.nvm"' }
    - { regexp: '^[[ -s "$NVM_DIR/nvm.sh" ]]', line: '[[ -s "$NVM_DIR/nvm.sh" ]] && \. "$NVM_DIR/nvm.sh"' }

- name: Installing node.js
  ansible.builtin.shell: source ~/.zshrc && nvm install node
  when: not nvm.stat.exists

- name: Install global node tools
  ansible.builtin.shell: npm install -g  {{ item }}
  loop: "{{ global_node_packages }}"
