- name: Checking for prior nvm package
  ansible.builtin.stat:
    path: ~/.nvm
  register: nvm

- name: Install nvm
  ansible.builtin.shell: bash -c "$(curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh)"
  when: not nvm.stat.exists

- name: Configure nvm with zsh
  ansible.builtin.lineinfile:
    path: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ zsh_conf }}"

- name: Installing node.js
  ansible.builtin.shell: source ~/.zshrc && nvm install node
  when: not nvm.stat.exists

- name: Install global node tools
  ansible.builtin.shell: npm install -g  {{ item }}
  loop: "{{ global_packages }}"
