- name: Checking for existing coursier install
  ansible.builtin.shell: cs list --help
  ignore_errors: True
  register: cs_exist_check

- name: Download coursier bootstrap
  ansible.builtin.get_url:
    url: https://git.io/coursier-cli-darwin
    dest: /tmp/cs
    mode: '0755'
  when: cs_exist_check.rc != 0

- name: Install coursier from bootstrap
  ansible.builtin.shell: /tmp/cs install cs
  when: cs_exist_check.rc != 0

- name: Add coursier to path
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: '^export PATH="$PATH:/Users/danhable/Library/Application Support/Coursier/bin"'
    line: 'export PATH="$PATH:/Users/danhable/Library/Application Support/Coursier/bin"'
    insertafter: EOF

- name: Updating coursier
  ansible.builtin.shell: cs update cs
  when: cs_exist_check.rc == 0

- name: Install base scala packages
  ansible.builtin.shell: source ~/.zshrc && cs install {{ item }}
  loop:
    - scala3-compiler
    - scala3-repl
    - ammonite
    - sbt
