gitignore_entries:
  - workspace.code-workspace
  - .vscode/

conf_entries:
  - { key: 'user.email',          value: '"dan@danhable.com"'   }
  - { key: 'user.name',           value: '"Dan Hable"'          }
  - { key: 'core.editor',         value: 'nvim'                 }  
  - { key: 'core.excludesfile',   value: '$HOME/.gitignore'     }
  - { key: 'core.pager',          value: 'bat'                  }
  - { key: 'diff.external',       value: 'difft'                }
  - { key: 'init.defaultBranch',  value: 'main'                 }
  - { key: 'alias.gone',          value: "! git fetch -p && git for-each-ref --format '%(refname:short) %(upstream:track)' | awk '$2 == \"[gone]\" {print $1}' | xargs -r git branch -D" }