- name: Checking for homebrew
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew

- name: Installing homebrew
  ansible.builtin.shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew.stat.exists

- name: Install jenv package
  community.general.homebrew:
    name: jenv
    state: latest
    update_homebrew: true

- name: Install jenv
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^export PATH="$HOME/.jenv/bin:$PATH"', line: 'export PATH="$HOME/.jenv/bin:$PATH"' }
    - { regexp: '^eval "$(jenv init -)"', line: 'eval "$(jenv init -)"' }

- name: Check for OpenJDK 11
  ansible.builtin.stat:
    path: /Library/Java/JavaVirtualMachines/openjdk-11.jdk
  register: openjdk11

- name: Install OpenJDK 11
  community.general.homebrew:
    name: openjdk@11
    state: latest
    update_homebrew: true

- name: System link OpenJDK 11
  become: yes
  ansible.builtin.shell: ln -sfn /usr/local/opt/openjdk@11/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk-11.jdk
  when: not openjdk11.stat.exists

- name: Add OpenJDK 11 to jenv
  ansible.builtin.shell: source ~/.zshrc && jenv add /Library/Java/JavaVirtualMachines/openjdk-11.jdk/Contents/Home
  when: not openjdk11.stat.exists

