- name: Install iTerm
  community.general.homebrew_cask:
    name: iterm2
    state: present
    accept_external_app: true

- name: Configure iterm
  ansible.builtin.shell: defaults write com.googlecode.iterm2 {{ item.key }} {{ item.type }} {{ item.value }}
  loop:
    - { key: 'QuitWhenAllWindowsClosed',      type: '-int', value: '0' }
    - { key: 'SUEnableAutomaticChecks',       type: '-int', value: '0' }
    - { key: 'SoundForEsc',                   type: '-int', value: '0' }
    - { key: 'VisualIndicatorForEsc',         type: '-int', value: '0' }
    - { key: 'PromptOnQuit',                  type: '-int', value: '1' }

