- name: Checking for existing oh-my-zsh install
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: omz

- name: Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not omz.stat.exists

- name: Configure zsh environment (common)
  ansible.builtin.lineinfile:
    path: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ zsh_conf.common }}"
