- name: Checking for existing oh-my-zsh install
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: omz

- name: Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: not omz.stat.exists

- name: Configure shell
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop: "{{ zshrc_cfg }}"

- name: Entries in gitignore file
  ansible.builtin.lineinfile:
    path: ~/.gitignore
    regexp: "{{ item }}"
    line: "{{ item }}"
  loop: "{{ global_gitignore }}"

- name: Setup global gitignore file
  ansible.builtin.shell: git config --global core.excludesfile $HOME/.gitignore