- name: Checking for homebrew
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: brew

- name: Installing homebrew
  ansible.builtin.shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew.stat.exists

- name: Updating homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Installing command line tools
  community.general.homebrew:
    name: "{{ common_packages + macosx_packages }}"
    state: latest
