- name: Mac OS X specific tasks
  import_tasks: macosx.yml
  when: ansible_facts['os_family']|lower == 'darwin'

- name: RedHat linux specific tasks
  import_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Common tasks
  import_tasks: common.yml

